app:
  name: "betera-tz"
  version: "1.0.0"
  env: "${APP_ENV}"
  logPath: "/logs/betera-tz.log"

server:
  host: "0.0.0.0"
  port: "${SERVER_PORT}"
  metricPort: "${METRIC_SERVER_PORT}"
  writeTimeout: 10s
  readTimeout: 10s
  idleTimeout: 30s
  requestTimeout: 10s
  closeTimeout: 30s

storage:
  user: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  database: "${POSTGRES_DB}"
  timezone: "Europe/Minsk"
  host: "postgres"
  port: "${POSTGRES_PORT}"
  sslMode: "${SSL_MODE}"
  connectTimeout: 10s
  pingTimeout: 5s
  amountOfConns: 15

queue:
  broker: "kafka:9092"
  topic: "tasks"
  groupId: "tasks-processing"
  timeout: 10s

monitoring:
  namespace: "betera-tz"
  