global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:

  - job_name: 'betera-tz'

    scrape_interval: 15s

    scrape_timeout: 15s

    static_configs:
      - targets: ['betera-tz:3334']