// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package dto

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TaskResponseStatus.
const (
	TaskResponseStatusCreated    TaskResponseStatus = "created"
	TaskResponseStatusDone       TaskResponseStatus = "done"
	TaskResponseStatusProcessing TaskResponseStatus = "processing"
)

// Defines values for GetTasksParamsStatusFilter.
const (
	GetTasksParamsStatusFilterCreated    GetTasksParamsStatusFilter = "created"
	GetTasksParamsStatusFilterDone       GetTasksParamsStatusFilter = "done"
	GetTasksParamsStatusFilterProcessing GetTasksParamsStatusFilter = "processing"
)

// ApiResponse defines model for ApiResponse.
type ApiResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Description string `json:"description"`
	Title       string `json:"title"`
}

// CreateTaskResponse defines model for CreateTaskResponse.
type CreateTaskResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	Status      TaskResponseStatus `json:"status"`
	Title       string             `json:"title"`
}

// TaskResponseStatus defines model for TaskResponse.Status.
type TaskResponseStatus string

// GetTasksParams defines parameters for GetTasks.
type GetTasksParams struct {
	Amount       *int                        `form:"amount,omitempty" json:"amount,omitempty"`
	Page         *int                        `form:"page,omitempty" json:"page,omitempty"`
	StatusFilter *GetTasksParamsStatusFilter `form:"statusFilter,omitempty" json:"statusFilter,omitempty"`
}

// GetTasksParamsStatusFilter defines parameters for GetTasks.
type GetTasksParamsStatusFilter string

// PatchTasksIdStatusParams defines parameters for PatchTasksIdStatus.
type PatchTasksIdStatusParams struct {
	Status string `form:"status" json:"status"`
}

// PostTasksJSONRequestBody defines body for PostTasks for application/json ContentType.
type PostTasksJSONRequestBody = CreateTaskRequest
